# ══════════════════════════════════════════════════════════════════════════════════
#  RUNG 4 — where secrets live.
#
#  COST: a DEFAULT vault with SOFTWARE-protected keys is Always Free, along with 150
#  secrets. VIRTUAL_PRIVATE vaults and HSM-protected keys are billed — this file uses
#  neither, and says so at each resource so a future edit has to be deliberate.
# ══════════════════════════════════════════════════════════════════════════════════

resource "oci_kms_vault" "main" {
  count = var.enable_vault ? 1 : 0

  compartment_id = var.compartment_ocid
  display_name   = "${var.instance_name}-vault"

  # ⚠ IMMUTABLE, and one-way. DEFAULT is the shared ("virtual") vault and is free;
  # VIRTUAL_PRIVATE is billed per hour and CANNOT be downgraded back.
  vault_type = "DEFAULT"

  freeform_tags = local.tags
}

resource "oci_kms_key" "main" {
  count = var.enable_vault ? 1 : 0

  compartment_id      = var.compartment_ocid
  display_name        = "${var.instance_name}-secrets-key"
  management_endpoint = oci_kms_vault.main[0].management_endpoint

  # SOFTWARE, not HSM. The free allowance covers a small number of HSM key versions, but
  # software keys avoid the capacity fee entirely — and "someone with physical access to
  # Oracle's datacentre" is not in the threat model for a hobby cluster.
  protection_mode = "SOFTWARE"

  key_shape {
    algorithm = "AES"
    length    = 32
  }

  freeform_tags = local.tags
}

# ── The one secret this repo can fill in for you ──────────────────────────────────
#
# With rungs 2 and 4 both on, Terraform already holds the tunnel token — so it writes it
# straight to the vault and the manual "pipe this into kubectl" step disappears. A rebuilt
# box fetches it itself, by being itself.
#
# This is the whole argument for rung 4 in one resource: the credential exists, but never
# on a laptop, never in a shell, and never on the instance's disk.
resource "oci_vault_secret" "cloudflared_token" {
  count = var.enable_vault && var.enable_cloudflare ? 1 : 0

  compartment_id = var.compartment_ocid
  vault_id       = oci_kms_vault.main[0].id
  key_id         = oci_kms_key.main[0].id
  secret_name    = "${var.instance_name}-cloudflared-token"
  description    = "Connector token for the Cloudflare tunnel. Written by terraform, read by External Secrets via instance principal."

  secret_content {
    content_type = "BASE64" # the only type OCI accepts; the value is base64 of the token
    content      = base64encode(data.cloudflare_zero_trust_tunnel_cloudflared_token.main[0].token)
  }
}

# ── Grafana's admin password ──────────────────────────────────────────────────────
#
# Generated rather than shipped as admin/admin. The old default asked you to log in with a
# well-known password and then change it — which means inventing one, remembering it, and
# re-doing it after every rebuild. People forget, and then reinstall Grafana to get back in.
#
# Now: Terraform generates it, cloud-init hands it to Kubernetes as a Secret, and
# `tofu output -raw grafana_admin_password` is the one place to read it. Nothing to invent,
# nothing to remember, and a rebuild produces the same answer because the value lives in
# state rather than in someone's head.
resource "random_password" "grafana_admin" {
  length = 24
  # Grafana's login form and a shell copy-paste both cope badly with quotes and backslashes.
  override_special = "-_.~"
}

# Stored in the vault too when rung 4 is on, so it is recoverable from the OCI console
# without a laptop that has the state file.
resource "oci_vault_secret" "grafana_admin" {
  count = var.enable_vault ? 1 : 0

  compartment_id = var.compartment_ocid
  vault_id       = oci_kms_vault.main[0].id
  key_id         = oci_kms_key.main[0].id
  secret_name    = "${var.instance_name}-grafana-admin"
  description    = "Grafana admin password. Generated by terraform; also delivered to the cluster at boot."

  secret_content {
    content_type = "BASE64"
    content      = base64encode(random_password.grafana_admin.result)
  }
}

# ── App secrets ───────────────────────────────────────────────────────────────────
#
# The apps in kubernetes/applications read their credentials from the vault through
# ExternalSecrets, and each vault entry's NAME is the app repo's `remoteRef.key`. The
# values are secrets, so they never live in this repo — but the mechanism does: put the
# name => value pairs in `app_vault_secrets` (via TF_VAR_ or a gitignored tfvars) and
# Terraform creates the entries, so a rebuilt box finds them with no console visit.
#
# The names are declassified for `for_each` (a resource instance key cannot be sensitive)
# while the values stay sensitive, so plan output never prints them.
resource "oci_vault_secret" "app" {
  for_each = var.enable_vault ? toset(nonsensitive(keys(var.app_vault_secrets))) : toset([])

  compartment_id = var.compartment_ocid
  vault_id       = oci_kms_vault.main[0].id
  key_id         = oci_kms_key.main[0].id
  secret_name    = each.key
  description    = "Application secret, created by terraform. Read by External Secrets via instance principal."

  secret_content {
    content_type = "BASE64"
    content      = base64encode(var.app_vault_secrets[each.key])
  }
}
