#!/usr/bin/env pwsh
# Print the SSH endpoint for the box. Shared by connect.ps1 and k9s.ps1.
#
# ONE resolution rule, in one place, so the scripts cannot drift apart. Terraform owns
# the address; this never hardcodes it and never reads local state.
#
#   1. an explicit argument            (an override, e.g. an address you know)
#   2. $env:SSH_HOST                   (an override for the session)
#   3. .ssh-endpoint in the repo root  (generated by `tofu apply` — see terraform/ssh-endpoint.tf)
#   4. `tofu output -raw public_ip`    (the authoritative source; needs state credentials)
#
# Only step 4 needs credentials. A box that has been applied once has the file, so the
# scripts run with none.
param([string]$Override)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent

$endpoint = $Override
if (-not $endpoint) { $endpoint = $env:SSH_HOST }

if (-not $endpoint) {
    $file = Join-Path $repoRoot '.ssh-endpoint'
    if ((Test-Path $file) -and (Get-Item $file).Length -gt 0) {
        $endpoint = (Get-Content $file -Raw).Trim()
    }
}

if (-not $endpoint) {
    $TF = if ($env:TF) { $env:TF }
          elseif (Get-Command tofu -ErrorAction SilentlyContinue) { 'tofu' }
          else { 'terraform' }
    Push-Location (Join-Path $repoRoot 'terraform')
    try {
        # A native command's stderr becomes a terminating error while the preference is
        # 'Stop', and a redirection does not stop that — so drop to 'Continue' around it
        # and let the exit code decide.
        $eap = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        $endpoint = (& $TF output -raw public_ip 2>$null)
        $ErrorActionPreference = $eap
    } finally {
        Pop-Location
    }
}

if (-not $endpoint) {
    [Console]::Error.WriteLine(
        "could not resolve the SSH endpoint. Run 'tofu apply' once (it writes .ssh-endpoint), " +
        "or export the state credentials and retry.")
    exit 1
}

$endpoint.Trim()
