#!/usr/bin/env bash
# Print the SSH endpoint for the box. Shared by connect.sh and k9s.sh.
#
# ONE resolution rule, in one place, so the scripts cannot drift apart. Terraform owns
# the address; this never hardcodes it and never reads local state.
#
#   1. an explicit argument            (an override, e.g. an address you know)
#   2. $SSH_HOST                       (an override for the session)
#   3. .ssh-endpoint in the repo root  (generated by `tofu apply` — see terraform/ssh-endpoint.tf)
#   4. `tofu output -raw public_ip`    (the authoritative source; needs state credentials)
#
# Only step 4 needs credentials. A box that has been applied once has the file, so the
# scripts run with none.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
endpoint="${1:-${SSH_HOST:-}}"

if [ -z "$endpoint" ] && [ -s "$repo_root/.ssh-endpoint" ]; then
    endpoint="$(cat "$repo_root/.ssh-endpoint")"
fi

if [ -z "$endpoint" ]; then
    TF="${TF:-tofu}"; command -v "$TF" >/dev/null 2>&1 || TF=terraform
    # `|| true`: under `set -e`, a failed `tofu output` (no state credentials) would abort
    # here, before the friendly message below could print.
    endpoint="$(cd "$repo_root/terraform" && "$TF" output -raw public_ip || true)"
fi

if [ -z "$endpoint" ]; then
    echo "could not resolve the SSH endpoint. Run 'tofu apply' once (it writes .ssh-endpoint)," \
         "or export the state credentials and retry." >&2
    exit 1
fi

printf '%s\n' "$endpoint"
