apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daftari-secrets
  namespace: daftari
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: daftari-secrets
    creationPolicy: Owner
  data:
    - secretKey: DAFTARI_TURSO_URL
      remoteRef:
        key: daftari-turso-url
    - secretKey: DAFTARI_TURSO_AUTH_TOKEN
      remoteRef:
        key: daftari-turso-auth-token
    - secretKey: DAFTARI_AUTH_SECRET
      remoteRef:
        key: daftari-auth-secret
